all:
	clang++ -g -I"." -o read_config main.cpp tinyxml/tinyxml.cpp tinyxml/tinystr.cpp \
	tinyxml/tinyxmlparser.cpp tinyxml/tinyxmlerror.cpp \
	tinyxml_template/fruits.cpp tinyxml_template/fruit.cpp tinyxml_template/gx_utils.cpp

clean:
	rm read_config
