'use strict';

const gxStrings = {
    ok: "确认",
    appMenuFile: "文件",
    appMenuOpenProject: "打开项目...",
    appMenuOpenFile: "打开...",
    appMenuOpenRecent: "打开最近",
    appMenuSaveFile: "保存",
    appMenuQuit: "退出",
    appMenuEdit: "编辑",
    appMenuUndo: "撤销",
    appMenuRedo: "重做",
    appMenuCut: "剪切",
    appMenuCopy: "复制",
    appMenuPaste: "粘贴",
    appMenuFind: "查找",
    appMenuSelectAll: "全选",
    appMenuView: "查看",
    appMenuModeEasy: "易读",
    appMenuModeRaw: "原生",
    appMenuHelp: "帮助",
    appMenuHomepage: "主页",
    appMenuDocument: "文档",
    appMenuAbout: "关于",
    appMenuAboutMessage: "版本 v",
    appMenuEmptyProject: "空项目",
    appMenuEmptyFile: "空文件",
    parseTmplFail: "模版文件解析失败",
    parseTmplFailDetail: "请在 www.bejson.com 或 Visual Code 编辑器中检查具体问题。模版路径已拷贝到剪切板。",
    openProjectFail: "打开工程错误",
    openProjectFailDetail: "不是合法的工程目录，目录内必须带gxproject.json。",
    revealInExplorer: "打开所在文件夹",
    openInWiki: "打开wiki",
    genDefaultTemplate: "生成默认模版",
    saveDataFileFail: "保存文件失败",
    saveDataFileFailDetail: "请先将当前文件改为可写或版本工具解锁。文件路径已拷贝到剪切板。",
    saveTmplFileFail: "保存模版文件失败",
    saveTmplFileFailDetail: "可能该文件已经存在并且只读，或者硬盘空间不够。",
    tmplRevealInExplorer: "打开模版所在文件夹",
    genCppCode: "生成cpp代码",
    render: "渲染",
    appMenuReload: "重载文件"
}

module.exports = gxStrings;
